### ISSUE TITLE
加载模型的节点在linux上无法正确加载

### ISSUE THREAD

**Issue by flybirdxx** [lldacing/ComfyUI_StableHair_ll#1]
![image](https://github.com/user-attachments/assets/d6fca47f-9d75-4744-8be4-205ba30736ec)
![image](https://github.com/user-attachments/assets/d862d487-f86d-4d91-a518-90a340d53373)
如截图中所示,两个模型加载节点没法正确显示,后台也没有任何报错信息,

**Comment by T8mars** [comment]
加载模型的节点在WINDOWS上也不行
![image](https://github.com/user-attachments/assets/6afb52b4-f4f5-4d1b-9e42-b6cbb8c9aa10)

**Comment by T8mars** [comment]
有BUG，没有选择CUDA的运行模式，只能选AUTO和CPU，选AUTO时候第一次和第二次可能不一致，导致第二次报错，建议加上CUDA选项呢

**Comment by T8mars** [comment]
![image](https://github.com/user-attachments/assets/a496108f-0621-426a-a814-d7091f26fbea)
d第一次光头时候换了几个图片都出现背景出问题的情况

**Comment by flybirdxx** [comment]
> ![image](https://private-user-images.githubusercontent.com/96167788/391302823-a496108f-0621-426a-a814-d7091f26fbea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMzEyNDYsIm5iZiI6MTczMzAzMDk0NiwicGF0aCI6Ii85NjE2Nzc4OC8zOTEzMDI4MjMtYTQ5NjEwOGYtMDYyMS00MjZhLWE4MTQtZDcwOTFmMjZmYmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDA1MjkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NmZkNjYzNjhmZGI3MmMxMGYyNGVhMzQ3Mjc3ZTVlMzYwN2Y2Y2FmNmMzNjI5MWQxYjVlNzM0ZWRiNDM2NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t8_xj_IDgeOWvH2ClL54L-qC5CE-IrbbojuXaFAkCVw) d第一次光头时候换了几个图片都出现背景出问题的情况

我在本地安装很正常,在云端加载模型的节点没办法正常加载,我也是了几个图背景都变了,而且跑起来很慢

**Comment by lldacing** [comment]
- 节点爆红是模型目录有.cache文件夹的原因，代码已修正，AUTO模式不能运行的问题也已修正

- 背景有东西这个，我把strength的范围上限调大了，可以调大试试，需要抽卡，应该是模型本身训练集的限制
