### ISSUE TITLE
大佬，效果图和参考图的发型会镜像

### ISSUE THREAD

**Issue by flybirdxx** [lldacing/ComfyUI_StableHair_ll#3]
![2b3eb7dd7cf4e23e32c4e12fb26334d](https://github.com/user-attachments/assets/d86488cc-6f6b-4d64-87b3-c4e37e59b44e)
如图所示，换发的图跟参考图头发会镜像，自己加镜像翻转会把人物反转，这个问题代码可以优化吗，

**Comment by lldacing** [comment]
> ![2b3eb7dd7cf4e23e32c4e12fb26334d](https://private-user-images.githubusercontent.com/26685745/391437309-d86488cc-6f6b-4d64-87b3-c4e37e59b44e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MzA1NzEsIm5iZiI6MTczNDQzMDI3MSwicGF0aCI6Ii8yNjY4NTc0NS8zOTE0MzczMDktZDg2NDg4Y2MtNmY2Yi00ZDY0LTg3YjMtYzRlMzdlNTliNDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDEwMTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYzZkZjQ4NjMyOWJkYzI4NmM5NDJmOTFmMmJmMzM2YTZmMjNjZTI2YjlmZmRjZWFhMTcwNWZiODdkZGNmZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TmtgKoXPaQguEYGXbRUDHpZoYLPvjKtBEQuthfzl75o) 如图所示，换发的图跟参考图头发会镜像，自己加镜像翻转会把人物反转，这个问题代码可以优化吗，

无从优化，我测试了一些图片，发现有的图是对的，有的图不行（即使把参考图先反转，结果图的发型方向还是固定的）
